/* ============================================================
   Centro de reportes · reportes institucionales generados del registro
   Cada reporte: vista previa imprimible (PDF), Excel (CSV) y envío por correo.
   ============================================================ */
(function () {
  const U = () => SIGA.ui;
  const M = (v, s) => U().money(v, s === undefined ? '' : s);
  const sum = (a, f) => a.reduce((s, x) => s + (f ? f(x) : x), 0);
  // Cada reporte devuelve { head:[..], rows:[[..]], pairs, total }
  const R = [
    ['Presupuesto', 'fa-file-invoice-dollar', 'Ejecución por genérica de gasto', 'PIM, devengado y avance por genérica', () => { const P = SIGA.data.presupuesto; return { head: ['Genérica', 'PIM', 'Devengado', 'Saldo', 'Avance %'], rows: P.genericas.map(g => [g.cod + ' ' + g.nom, M(g.pim), M(g.dev), M(g.pim - g.dev), (g.dev / g.pim * 100).toFixed(1)]) }; }],
    ['Presupuesto', 'fa-file-invoice-dollar', 'Ejecución por fuente de financiamiento', 'PIM, certificado y devengado por fuente', () => { const P = SIGA.data.presupuesto; return { head: ['Fuente', 'PIM', 'Certificado', 'Devengado', 'Avance %'], rows: P.fuentes.map(f => [f.cod + ' ' + f.nom, M(f.pim), M(f.cert), M(f.dev), (f.dev / f.pim * 100).toFixed(1)]) }; }],
    ['Presupuesto', 'fa-file-invoice-dollar', 'Certificaciones del periodo', 'CCP con fase, centro de costo y clasificador', () => ({ head: ['CCP', 'Fecha', 'Centro de costo', 'Clasificador', 'Fase', 'Monto'], rows: SIGA.data.presupuesto.certificaciones.map(c => { const m = SIGA.ppto.marco(c.marco); return [c.num, c.fecha, m.ccn, m.clasif, c.fase, M(c.monto)]; }) })],
    ['Presupuesto', 'fa-file-invoice-dollar', 'Marco presupuestal y saldos', 'Disponibilidad por específica con semáforo', () => ({ head: ['Llave', 'Centro de costo', 'Clasificador', 'PIM', 'Certificado', 'Saldo'], rows: SIGA.data.presupuesto.marco.map(m => [m.id, m.ccn, m.clasif + ' ' + m.desc, M(m.pim), M(SIGA.ppto.certificado(m)), M(SIGA.ppto.saldo(m))]) })],
    ['Presupuesto', 'fa-file-invoice-dollar', 'Notas modificatorias', 'Créditos, habilitaciones y anulaciones', () => ({ head: ['Nota', 'Fecha', 'Tipo', 'Fuente', 'Concepto', 'Habilita', 'Anula'], rows: SIGA.data.presupuesto.notas.map(n => [n.n, n.fecha, n.tipo, n.fte, n.concepto, M(n.hab), M(n.anu)]) })],
    ['Logística', 'fa-boxes-stacked', 'Órdenes de compra y servicio', 'Por proveedor, certificación y estado', () => ({ head: ['Documento', 'Fecha', 'Proveedor', 'CCP', 'Estado', 'Importe'], rows: SIGA.data.abastecimiento.ordenes.map(o => [o.doc, o.fecha, o.prov, o.cert, o.estado, M(o.imp)]) })],
    ['Logística', 'fa-boxes-stacked', 'Compras por proveedor', 'Monto acumulado de órdenes vigentes', () => { const g = {}; SIGA.data.abastecimiento.ordenes.filter(o => o.estado !== 'Anulada').forEach(o => { g[o.prov] = g[o.prov] || [0, 0]; g[o.prov][0]++; g[o.prov][1] += o.imp; }); return { head: ['Proveedor', 'Órdenes', 'Monto'], rows: Object.entries(g).sort((a, b) => b[1][1] - a[1][1]).map(([p, v]) => [p, v[0], M(v[1])]) }; }],
    ['Logística', 'fa-boxes-stacked', 'Requerimientos por estado', 'Seguimiento de la aprobación electrónica', () => ({ head: ['N.º', 'Fecha', 'Centro de costo', 'Descripción', 'Estado', 'Monto'], rows: SIGA.data.abastecimiento.requerimientos.map(r => [r.num, r.fecha, r.cc, r.desc, r.estado, M(r.monto)]) })],
    ['Logística', 'fa-boxes-stacked', 'Plan Anual de Contrataciones', 'Procedimientos y etapa', () => ({ head: ['Procedimiento', 'Objeto', 'Tipo', 'Trimestre', 'Etapa', 'Valor estimado'], rows: SIGA.data.abastecimiento.pac.map(p => [p[0], p[1], p[2], p[4], p[5], M(p[3])]) })],
    ['Almacén', 'fa-warehouse', 'Inventario valorizado de existencias', 'Stock, costo promedio y valor', () => { const L = SIGA.data.almacen; return { head: ['Código', 'Bien', 'Ubicación', 'Stock', 'C. prom.', 'Valor'], rows: L.items.map(i => [i.cod, i.desc, i.ubic, i.stock + ' ' + i.um, SIGA.alm.cprom(i.cod).toFixed(4), M(i.stock * SIGA.alm.cprom(i.cod))]), total: M(sum(L.items, i => i.stock * SIGA.alm.cprom(i.cod))) }; }],
    ['Almacén', 'fa-warehouse', 'Bienes bajo stock mínimo', 'Propuesta de reposición mín.–máx.', () => ({ head: ['Código', 'Bien', 'Stock', 'Mínimo', 'Máximo', 'Sugerido'], rows: SIGA.data.almacen.items.filter(i => i.stock < i.min).map(i => [i.cod, i.desc, i.stock, i.min, i.max, Math.max(0, i.max - i.stock)]) })],
    ['Almacén', 'fa-warehouse', 'Movimientos de almacén (PECOSA y NEA)', 'Despachos y recepciones del mes', () => ({ head: ['Documento', 'Fecha', 'Bien', 'Dependencia', 'Cantidad', 'Estado'], rows: SIGA.data.almacen.movs.map(m => [m.doc, m.fecha, m.item, m.dep, m.cant, m.estado]) })],
    ['Patrimonio', 'fa-building-columns', 'Bienes por responsable', 'Asignaciones en uso', () => ({ head: ['Responsable', 'Código', 'Bien', 'Local', 'Estado', 'Valor'], rows: SIGA.data.patrimonio.bienes.filter(b => b.situacion !== 'Baja').sort((a, b) => a.resp.localeCompare(b.resp)).map(b => [b.resp, b.cod, b.desc, b.local, b.estado, M(b.valor)]) })],
    ['Patrimonio', 'fa-building-columns', 'Bajas patrimoniales', 'Causal, informe y resolución', () => ({ head: ['N.º', 'Fecha', 'Bien', 'Causal', 'Resolución', 'Valor'], rows: SIGA.data.patrimonio.bajas.map(b => [b.num, b.fecha, b.bien, b.causal, b.resol || b.estado, M(b.valor)]) })],
    ['Tesorería', 'fa-money-check-dollar', 'Comprobantes de pago', 'Girados y pagados con retenciones', () => ({ head: ['C/P', 'Fecha', 'Beneficiario', 'Bruto', 'Det./ret.', 'Neto', 'Estado'], rows: SIGA.data.tesoreria.cp.map(c => [c.doc, c.fecha, c.benef, M(c.bruto), M(c.detr + c.ret), M(c.neto), c.estado]) })],
    ['Tesorería', 'fa-money-check-dollar', 'Saldos bancarios', 'Libros frente a extracto', () => ({ head: ['Banco', 'Cuenta', 'Fuente', 'Libros', 'Extracto', 'Diferencia'], rows: SIGA.data.tesoreria.bancos.map(b => [b.banco, b.cta, b.fte, M(b.libros), M(b.extracto), M(b.libros - b.extracto)]) })],
    ['Tesorería', 'fa-money-check-dollar', 'Detracciones y retenciones', 'Constancias SPOT y renta de 4.ª', () => ({ head: ['C/P', 'Beneficiario', 'RUC', 'Detracción', 'Retención 4.ª'], rows: SIGA.data.tesoreria.cp.filter(c => c.detr || c.ret).map(c => [c.doc, c.benef, c.ruc, M(c.detr), M(c.ret)]) })],
    ['Tesorería', 'fa-file-invoice', 'Obligaciones por vencer y antigüedad', 'Cuentas por pagar a proveedores', () => ({ head: ['Documento', 'Proveedor', 'Vencimiento', 'Días', 'Estado', 'Importe'], rows: SIGA.data.ctaper.obligaciones.filter(o => o.estado !== 'Pagado').map(o => [o.doc, o.prov, o.venc, o.dias, o.estado, M(o.imp)]) })],
    ['Contabilidad', 'fa-book', 'Balance de comprobación', 'Sumas y saldos al día', () => { const K = SIGA.data.contabilidad, b = {}; Object.entries(K.base).forEach(([c, v]) => b[c] = [v[0], v[1]]); K.asientos.forEach(a => a.lineas.forEach(l => { b[l.cta] = b[l.cta] || [0, 0]; b[l.cta][0] += l.debe; b[l.cta][1] += l.haber; })); return { head: ['Cuenta', 'Denominación', 'Debe', 'Haber', 'Saldo'], rows: Object.keys(b).sort().map(c => [c, K.plan[c] || '', M(b[c][0]), M(b[c][1]), M(b[c][0] - b[c][1])]) }; }],
    ['Contabilidad', 'fa-book', 'Libro diario del mes', 'Asientos automáticos y manuales', () => { const rows = []; SIGA.data.contabilidad.asientos.forEach(a => a.lineas.forEach((l, i) => rows.push([i ? '' : a.num, i ? '' : a.fecha, i ? '' : a.glosa, l.cta, l.debe ? M(l.debe) : '', l.haber ? M(l.haber) : '']))); return { head: ['Asiento', 'Fecha', 'Glosa', 'Cuenta', 'Debe', 'Haber'], rows }; }],
    ['Contabilidad', 'fa-book', 'Activos fijos y depreciación', 'Valor, depreciación acumulada y neto', () => ({ head: ['Código', 'Bien', 'Cuenta', 'Valor', 'Tasa', 'Situación'], rows: SIGA.data.patrimonio.bienes.map(b => [b.cod, b.desc, b.cuenta, M(b.valor), b.tasa + '%', b.situacion]) })],
    ['RR.HH.', 'fa-users', 'Planilla por régimen laboral', 'Ingresos, descuentos, aportes y neto', () => ({ head: ['Régimen', 'Trabajadores', 'Ingresos', 'Descuentos', 'Aportes', 'Neto'], rows: SIGA.data.planilla.regimenes.map(r => [r[0] + ' ' + r[1], r[2], M(r[3]), M(r[4]), M(r[5]), M(r[3] - r[4])]) })],
    ['RR.HH.', 'fa-users', 'Relación de trabajadores', 'Legajo digital · régimen y dependencia', () => ({ head: ['Código', 'Cargo', 'Régimen', 'Dependencia', 'Pensiones', 'Condición'], rows: SIGA.data.planilla.trabajadores.map(t => [t.cod, t.cargo, t.reg, t.dep, t.sis, t.cond]) })],
    ['RR.HH.', 'fa-gavel', 'Retenciones judiciales', 'Mandatos, porcentaje y depósito', () => ({ head: ['Expediente', 'Trabajador', 'Concepto', '%', 'Monto', 'Beneficiario'], rows: SIGA.data.ctaper.judiciales.map(j => [j.exp, j.trab, j.concepto, j.pct, M(j.monto), j.benef]) })],
    ['Producción', 'fa-industry', 'Resultado por unidad productiva', 'Ingresos, costos y margen', () => ({ head: ['Unidad', 'Tipo', 'Ingresos', 'Costos', 'Resultado', 'Margen %'], rows: SIGA.data.produccion.unidades.map(u => [u.nom, u.tipo, M(u.ing), M(u.cos), M(u.ing - u.cos), u.ing ? ((u.ing - u.cos) / u.ing * 100).toFixed(1) : '—']) })],
    ['Producción', 'fa-industry', 'Costo unitario real por producto', 'Insumos, mano de obra, depreciación y merma', () => ({ head: ['Producto', 'Unidad', 'Costo unitario', 'Precio', 'Margen %'], rows: SIGA.data.produccion.costos.map(c => { const cu = (c[2] + c[3] + c[4] + c[5]) * (1 + c[6] / 100); return [c[0], c[1], cu.toFixed(2), c[7].toFixed(2), ((c[7] - cu) / c[7] * 100).toFixed(1)]; }) })],
    ['Producción', 'fa-diagram-project', 'Trazabilidad de lotes de producto terminado', 'Materia prima, orden, distribución y estado del lote', () => { const D = SIGA.mrp.distribucion(); return { head: ['Lote', 'Producto', 'Orden', 'Producción', 'Vence', 'Producido', 'Distribuido', 'Clientes', 'Materia prima', 'Estado'], rows: SIGA.data.produccion.lotesPT.map(l => [l.lote, l.prod, l.op, l.f, l.venc, l.cant, l.previo + (D.asig[l.lote] || 0), (D.out[l.lote] || []).length, (l.mp || []).join(' · '), l.estado]) }; }],
    ['Producción', 'fa-flask-vial', 'Control de calidad de materia prima', 'Recepciones, parámetros fuera de especificación y dictamen', () => ({ head: ['Recepción', 'Fecha', 'Materia prima', 'Proveedor', 'Cantidad', 'Fuera de especificación', 'Dictamen'], rows: SIGA.data.produccion.recepciones.map(r => [r.id, r.f, r.mp, r.prov, r.cant + ' ' + r.um, r.estado === 'Pendiente de análisis' ? '—' : SIGA.mrp.dictamen(r.mp, r.res)[1].map(x => x[0]).join(' · ') || 'Ninguno', r.estado]) })],
    ['Producción', 'fa-screwdriver-wrench', 'Plan de mantenimiento de equipos', 'Próximo preventivo, disponibilidad y costo por equipo', () => ({ head: ['Equipo', 'Unidad', 'Criticidad', 'Horas', 'Próximo', 'Situación', 'Fallas 12 m', 'Costo 12 m', 'Estado'], rows: SIGA.data.produccion.equipos.map(e => { const p = SIGA.mrp.prox(e); return [e.cod + ' ' + e.nom, e.unidad, e.crit, e.horas, p.txt, p.venc ? 'Vencido' : p.cerca ? 'Próximo' : 'Al día', e.fallas, M(e.costo12), e.estado]; }) })],
    ['Pecuario', 'fa-cow', 'Indicadores zootécnicos por especie', 'Valor calculado frente a la meta de cada unidad', () => { const rows = []; Object.values(SIGA.data.pecuario.especies).forEach(e => SIGA.pec.BENCH[e.key](e, SIGA.pec.KP[e.key](e)).forEach(b => rows.push([e.nombre, b[0], (+b[1] || 0).toFixed(b[3]) + (b[5] ? ' ' + b[5] : ''), (+b[2]).toFixed(b[3]) + (b[5] ? ' ' + b[5] : ''), { ok: 'En meta', warn: 'Cerca', bad: 'Bajo meta' }[SIGA.pec.semaf(b[1], b[2], b[4])]]))); return { head: ['Especie', 'Indicador', 'Valor', 'Meta', 'Estado'], rows }; }],
    ['Pecuario', 'fa-syringe', 'Tratamientos y períodos de retiro', 'Registro de medicamentos veterinarios (inocuidad)', () => { const rows = []; Object.values(SIGA.data.pecuario.especies).forEach(e => e.trat.forEach(t => { const f0 = SIGA.pec.addD(t.f, t.dias); rows.push([t.id, e.nombre, t.f, t.ref, t.diag, t.prod, t.retC ? SIGA.pec.addD(f0, t.retC) : '—', t.retL ? SIGA.pec.addD(f0, t.retL) : '—', t.vet, t.estado]); })); return { head: ['N.º', 'Especie', 'Fecha', 'Animal / lote', 'Diagnóstico', 'Producto', 'Retiro carne hasta', 'Retiro leche hasta', 'Veterinario', 'Estado'], rows }; }],
    ['Pecuario', 'fa-truck', 'Movilización de animales y CSTI', 'Sacas, ventas, compras y traslados con su certificado', () => { const rows = []; Object.values(SIGA.data.pecuario.especies).forEach(e => e.mov.forEach(m => rows.push([m.id, e.nombre, m.f, m.tipo, m.ref, m.cant, m.kg, m.destino, m.csti || 'interno', m.doc]))); return { head: ['N.º', 'Especie', 'Fecha', 'Tipo', 'Animales', 'Cabezas', 'Kg', 'Destino', 'CSTI', 'Documento'], rows }; }],
    ['Producción', 'fa-receipt', 'Registro de ventas', 'Formato 14.1 · comprobantes electrónicos', () => ({ head: ['Comprobante', 'Fecha', 'Cliente', 'Base', 'IGV', 'Total', 'SUNAT'], rows: SIGA.data.ventas.comprobantes.map(c => [c.doc, c.fecha, c.cli, M(c.anulado ? 0 : c.grav + c.exon), M(c.anulado ? 0 : c.igv), M(c.anulado ? 0 : c.total), c.anulado ? 'Anulado' : c.sunat]) })],
    ['Producción', 'fa-sack-dollar', 'Recaudación RDR por unidad', 'Recibos de ingreso por clasificador', () => { const g = {}; SIGA.data.caja.ingresos.filter(r => !r.anulado).forEach(r => { g[r.unidad] = g[r.unidad] || [0, 0, r.clasif]; g[r.unidad][0]++; g[r.unidad][1] += r.total; }); return { head: ['Unidad productiva', 'Clasificador', 'Recibos', 'Recaudado'], rows: Object.entries(g).sort((a, b) => b[1][1] - a[1][1]).map(([u, v]) => [u, v[2], v[0], M(v[1])]) }; }],
    ['Control', 'fa-shield-halved', 'Bitácora de auditoría', 'Operaciones con usuario, IP y valores', () => ({ head: ['Fecha y hora', 'Usuario', 'Módulo', 'Acción', 'Referencia', 'Antes', 'Después'], rows: SIGA.data.seguridad.bitacora.map(b => [b.ts, b.user, b.mod, b.acc, b.ref, b.antes, b.despues]) })],
    ['Control', 'fa-right-left', 'Transmisiones a SIAF-SP y SUNAT', 'Bandeja de salida y respuestas', () => ({ head: ['#', 'Fecha', 'Destino', 'Operación', 'Referencia', 'Estado', 'Respuesta'], rows: SIGA.data.integracion.msgs.map(m => [m.id, m.ts, m.sistema, m.tipo, m.ref, m.estado, m.resp]) })],
    ['Control', 'fa-route', 'Expedientes y tiempos de trámite', 'Recorrido del gasto por expediente', () => ({ head: ['Expediente', 'Asunto', 'Centro de costo', 'Importe', 'Etapas'], rows: SIGA.data.expediente.lista.map(e => [e.id, e.asunto, e.cc, M(e.monto), Object.keys(e.pasos).length + ' de 7']) })]
  ];
  const PROG = [['Ejecución presupuestal por genérica', 'Rectorado · DGA', 'Lunes 07:00', 'Correo con PDF'], ['Obligaciones por vencer', 'Tesorería', 'Diario 07:30', 'Correo con Excel'], ['Bienes bajo stock mínimo', 'Abastecimiento', 'Diario 08:00', 'Alerta en la bandeja'], ['Bitácora de auditoría', 'Órgano de Control Institucional', 'Mensual día 1', 'Archivo firmado']];

  function generar(r, modo) {
    const u = U(), d = r[4](), file = 'reporte_' + r[2].toLowerCase().normalize('NFD').replace(/[^a-z0-9]+/g, '_');
    SIGA.log('Reportes', 'Generación de reporte', r[2], '—', d.rows.length + ' filas');
    if (modo === 'csv') { u.csv(file, d.head, d.rows.map(x => x.map(v => u.strip(String(v))))); return; }
    const body = `<table class="doc-tbl"><thead><tr>${d.head.map((h, i) => `<th class="${i && /Monto|Importe|PIM|Devengado|Certificado|Saldo|Valor|Debe|Haber|Neto|Bruto|Ingresos|Descuentos|Aportes|Costos|Resultado|Total|Base|IGV|Recaudado|Libros|Extracto|Diferencia|Habilita|Anula|Detracción|Retención/.test(h) ? 'r' : ''}">${h}</th>`).join('')}</tr></thead><tbody>${d.rows.map(x => `<tr>${x.map((v, i) => `<td class="${i && /Monto|Importe|PIM|Devengado|Certificado|Saldo|Valor|Debe|Haber|Neto|Bruto|Ingresos|Descuentos|Aportes|Costos|Resultado|Total|Base|IGV|Recaudado|Libros|Extracto|Diferencia|Habilita|Anula|Detracción|Retención/.test(d.head[i]) ? 'r' : ''}">${u.esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
    u.preview(r[2], u.doc({ tipo: 'Reporte · ' + r[0], num: r[2], office: 'SIGA-U · Centro de reportes', pairs: [['Descripción', r[3], 1], ['Registros', d.rows.length], ['Generado por', SIGA.ctx.user.nombre + ' · ' + SIGA.ctx.user.rolTx], ...(d.total ? [['Total', d.total]] : [])], body }), { file, csv: () => u.csv(file, d.head, d.rows.map(x => x.map(v => u.strip(String(v))))) });
  }

  SIGA.registerModule('reportes', {
    title: 'Centro de reportes', icon: 'fa-chart-pie', group: 'Configuración y control', badge: 'NUEVO', badgeNew: true,
    cat: 'Todos',
    search(q) { return R.filter(r => (r[2] + ' ' + r[3] + ' ' + r[0]).toLowerCase().includes(q)).map(r => ({ t: 'Reporte · ' + r[2], d: r[0] + ' · ' + r[3], fn: () => generar(r) })); },
    render(el) {
      const u = U(), cats = ['Todos', ...new Set(R.map(r => r[0]))], rows = R.filter(r => this.cat === 'Todos' || r[0] === this.cat);
      el.innerHTML = `
      <div class="page-head"><div><h1>Centro de reportes</h1><p>${R.length} reportes institucionales generados del mismo registro que usan los módulos · vista previa imprimible, Excel y envío por correo · sin armado manual en hojas de cálculo</p></div></div>
      ${u.kpis([{ lab: 'Reportes disponibles', val: R.length, sub: (cats.length - 1) + ' áreas' }, { lab: 'Formatos', val: 'PDF · Excel', sub: 'con código QR de verificación' }, { lab: 'Reportes programados', val: PROG.length, sub: 'envío automático por correo' }, { lab: 'Tiempo de elaboración', val: 'segundos', sub: 'antes: días de consolidación manual', chip: '−99%' }])}
      <div class="toolbar"><div class="chips" id="rp-c">${cats.map(c => `<span class="chipf ${c === this.cat ? 'on' : ''}" data-c="${c}">${c}${c === 'Todos' ? '' : ' · ' + R.filter(r => r[0] === c).length}</span>`).join('')}</div></div>
      <div class="grid cols-4 mb rp-grid">${rows.map(r => `<div class="card rp" data-i="${R.indexOf(r)}"><div class="rp-h"><i class="fa-solid ${r[1]}"></i><span>${r[0]}</span></div><b>${r[2]}</b><p class="mini">${r[3]}</p>
        <div class="row-flex mt"><button class="btn sm" data-g="pdf"><i class="fa-solid fa-print"></i> Ver / PDF</button><button class="btn sm ghost" data-g="csv"><i class="fa-solid fa-file-excel"></i> Excel</button><button class="btn sm ghost" data-g="mail" title="Enviar por correo"><i class="fa-solid fa-envelope"></i></button></div></div>`).join('')}</div>
      <div class="card"><h3><span class="dot"></span>Reportes programados <span class="grow">se envían solos a sus destinatarios</span></h3><div id="rp-p"></div></div>`;
      el.querySelector('#rp-c').addEventListener('click', e => { const c = e.target.closest('[data-c]'); if (c) { this.cat = c.dataset.c; SIGA.refresh(); } });
      el.querySelectorAll('.rp').forEach(c => c.addEventListener('click', e => { const r = R[+c.dataset.i], b = e.target.closest('[data-g]'); if (b && b.dataset.g === 'mail') { u.mail({ asunto: r[2] + ' · SIGA-U', adj: r[2].replace(/\W+/g, '_') + '.pdf' }); return; } generar(r, b ? b.dataset.g : 'pdf'); }));
      const pRec = { mod: 'Reportes', tipo: 'Programación de reporte', key: p => 'PRG ' + p[0], title: p => p[0], cls: false, estado: 4, anuladoValor: 'Suspendido',
        fields: p => [['Reporte', p[0]], ['Destinatarios', p[1]], ['Frecuencia', p[2]], ['Entrega', p[3]], ['Estado', p[4] || 'Activo']],
        edit: [{ k: 'd', label: 'Destinatarios', get: p => p[1], set: (p, v) => p[1] = v }, { k: 'f', label: 'Frecuencia', type: 'select', options: ['Diario 07:30', 'Diario 08:00', 'Lunes 07:00', 'Mensual día 1'], get: p => p[2], set: (p, v) => p[2] = v }],
        extra: p => [{ icon: 'fa-paper-plane', label: 'Enviar ahora', fn: x => { const r = R.find(k => k[2].startsWith(x[0].split(' ')[0])) || R[0]; generar(r); } }],
        anular: true, anularLabel: 'Suspender envío', canAnular: p => (p[4] || 'Activo') === 'Activo' };
      document.getElementById('rp-p').innerHTML = u.grid({ id: 'rep-prog', title: 'programados', rows: PROG, record: pRec, search: false, cols: [{ k: 0, label: 'Reporte', render: p => `<b>${p[0]}</b>` }, { k: 1, label: 'Destinatarios' }, { k: 2, label: 'Frecuencia' }, { k: 3, label: 'Entrega' }, { k: 4, label: 'Estado', render: p => u.tag(p[4] || 'Activo', (p[4] || 'Activo') === 'Activo' ? 't-green' : 't-gray') }],
        tools: [{ icon: 'fa-plus', label: 'Programar reporte', primary: true, fn: () => u.formModal('<i class="fa-solid fa-clock"></i> Programar reporte', [{ k: 'r', label: 'Reporte', type: 'select', options: R.map(r => r[2]) }, { k: 'd', label: 'Destinatarios', value: 'dga@unas.edu.pe' }, { k: 'f', label: 'Frecuencia', type: 'select', options: ['Diario 07:30', 'Lunes 07:00', 'Mensual día 1'], span: 1 }, { k: 'e', label: 'Entrega', type: 'select', options: ['Correo con PDF', 'Correo con Excel', 'Alerta en la bandeja'], span: 1 }], v => { PROG.push([v.r, v.d, v.f, v.e]); SIGA.log('Reportes', 'Programación de reporte', v.r, '—', v.f + ' · ' + v.d); u.closeModal(); SIGA.refresh(); u.toast('Reporte programado · ' + v.f); }, 'Programar') }] });
    }
  });
})();
